### ISSUE TITLE
not an issue, but a request

### ISSUE THREAD

**Issue by dstoe75** [BackTrak/StreamDeckNvidiaBroadcastPlugin#4]
Hi,
thanks for your program, which works smoothly.
Would it be possible to add an option to the "background replacement", so that I could choose different files? That way, I could set multiple background replacement buttons, each linked to a different video background.

cheers,
Dominik

**Comment by BackTrak** [comment]
It's a great suggestion, I played around with it today, but because the edit control is not a real text box and is just a read only button with a file picker hooked to it AND the file picker can only be displayed when nVidia Broadcast is maximized, I don't have a way to switch the graphic. Unfortunately, StreamDeck plugins are not allowed to run in Admin mode. This is a store requirement, so I cannot use any debugger / memory access tricks to force the graphic to change. If anyone can think of a method to use to swap the graphic, without terminated Broadcast or running in Admin mode, let me know! I was thinking to modify the config file with the background replace on, then restart Broadcast, but it would interrupt your camera while it restarts... Not smooth!

**Comment by BackTrak** [comment]
Hi @dstoe75 , thinking more about this one, you could just do it within OBS studio, no need to mess with NVidia Broadcast at all. Simply create some image sources in OBS Studio, pointing to the pictures you want to use as a background. Move them under your camera layer. Then use NVidia Broadcast's Background removal filter to remove your camera background. When you put the image source under your NVidia Camera Source in OBS, then you can just toggle image source visibility using Stream Deck's OBS plugin. So, on the StreamDeck, you would have one button to toggle background removal and then several buttons to toggle your desired background image. If you wanted to get fancy, you could use a multi-action button to turn off all of your backgrounds, then turn on the one you want. Let me know if you get stuck!

Thanks,
Nick.

**Comment by dstoe75** [comment]
HI Nick,
thanks for the input, this is basically, where I am coming from. My first
approach was using vMix (same as OBS), then I used only Elgatos Camera Hub
feature, thinking, that is a much slimmer solution, but I constantly
struggled with freezes and crashes of Elgatos Camera Hub software. That
brought me to Nvidia Broadcast, which is stable, but lacks API features.
I will probably go back to vmix then.
Thanks for your help though

**Comment by BackTrak** [comment]
You should be able to use nVidia broadcast with vMix as a camera source so that you get the best of both worlds without using Elgato Camera Hub. Hopefully it will be stable for you!
